name: "TESTING NOTEBOOK"

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build_pip:
    name: Linux jupyter
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 nbconvert[test]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test
      run: |
        jupyter nbconvert --execute brain_age_starting_kit.ipynb --to html --ExecutePreprocessor.kernel_name=python3
